sonar.projectKey=Freya-Tenebrae_MEWO_dev_ops
sonar.organization=Freya-Tenebrae

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.11
sonar.python.coverage.reportPaths=./coverage.xml
sonar.python.xunit.reportPath=./test-results.xml

sonar.sourceEncoding=UTF-8
